### ISSUE TITLE
О, классно. Что писать будешь?

### ISSUE THREAD

**Issue by ptrofimov** [iomakarov/iomakarov.github.io#1]

**Comment by iomakarov** [comment]
Привет! Я запихну сюда все свои стихи! Это будет маленькая андеграундная страничка, где будет 10 строк кода и много русских букв)))

**Comment by iomakarov** [comment]
Устал я от фреймворков, баз данных, и т.п. Хочется для души чего-нибудь сверх простого и удобного)))
